name: Java CI

on:
  push:
    paths:
     - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      
      - name: Prepare S3 upload target 
        run: mkdir artifacts && cp target/*.jar artifacts/

      - name: install aws cli
        run: sudo apt-get update && sudo apt-get install -y awscli
      
      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id = ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        
      - name: build a docker image
        run: mvn spring-boot:build-image
        
        
      - name: login to aws ecr  
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 702620960245.dkr.ecr.ap-south-1.amazonaws.com
        
      - name: list down docker images
        run: docker image ls
        
      - name: tag a docker image 
        run: docker tag springboot_simple:0.0.1-SNAPSHOT 702620960245.dkr.ecr.ap-south-1.amazonaws.com/monil2311-registry
        
      - name: push docker image
        run: docker push 702620960245.dkr.ecr.ap-south-1.amazonaws.com/monil2311-registry
        
       
       


